In [57]:
import json
import pandas as pd

In [60]:
# model_name = 'Llama3Point2Vision90B'
model_name = 'Gemini1Point5Pro'

queries_file = f'../../data/synthTRIPS/generated-queries/{model_name}_generated_queries.json'

with open(queries_file, 'r') as f:
    queries = json.load(f)
len(queries)

2302

In [61]:
queries[0]

{'config_id': 'c_p_0_pop_low_easy',
 'config': {'p_id': 'p_0',
  'persona': 'A top-scoring player in the local league who is also eyeing a professional career in the NHL',
  'filters': {'popularity': 'low', 'month': 'February'}},
 'context': 'Adana has low popularity. Adana has low season in February. \nAdiyaman has low popularity. Adiyaman has low season in February. \nAgri has low popularity. Agri has low season in February. \nArad has low popularity. Arad has low season in February. \nArkhangelsk has low popularity. Arkhangelsk has low season in February. \nBacau has low popularity. Bacau has low season in February. \nBaia Mare has low popularity. Baia Mare has low season in February. \nBalikesir has low popularity. Balikesir has low season in February. \nBrest has low popularity. Brest has low season in February. \nBurgas has low popularity. Burgas has low season in February. \nCanakkale has low popularity. Canakkale has low season in February. \nCraiova has low popularity. Craiova has low season in February. \nDebrecen has low popularity. Debrecen has low season in February. \nDenizli has low popularity. Denizli has low season in February. \nDiyarbakir has low popularity. Diyarbakir has low season in February. \nElazig has low popularity. Elazig has low season in February. \nErzincan has low popularity. Erzincan has low season in February. \nEskisehir has low popularity. Eskisehir has low season in February. \nGaziantep has low popularity. Gaziantep has low season in February. \nIasi has low popularity. Iasi has low season in February. \nIoannina has low popularity. Ioannina has low season in February. \nIsparta has low popularity. Isparta has low season in February. \nJonkoping has low popularity. Jonkoping has low season in February. \nKahramanmaras has low popularity. Kahramanmaras has low season in February. \nKars has low popularity. Kars has low season in February. \nKayseri has low popularity. Kayseri has low season in February. \nKonya has low popularity. Konya has low season in February. \nKosice has low popularity. Kosice has low season in February. \nLinkoping has low popularity. Linkoping has low season in February. \nMalatya has low popularity. Malatya has low season in February. \nMiskolc has low popularity. Miskolc has low season in February. \nMykolaiv has low popularity. Mykolaiv has low season in February. \nNalchik has low popularity. Nalchik has low season in February. \nNevsehir has low popularity. Nevsehir has low season in February. \nNis has low popularity. Nis has low season in February. \nOrebro has low popularity. Orebro has low season in February. \nOrleans has low popularity. Orleans has low season in February. \nRivne has low popularity. Rivne has low season in February. \nRzeszow has low popularity. Rzeszow has low season in February. \nSamsun has low popularity. Samsun has low season in February. \nSanliurfa has low popularity. Sanliurfa has low season in February. \nSevilla has low popularity. Sevilla has low season in February. \nSiirt has low popularity. Siirt has low season in February. \nSivas has low popularity. Sivas has low season in February. \nSyktyvkar has low popularity. Syktyvkar has low season in February. \nTargu-Mures has low popularity. Targu-Mures has low season in February. \nTekirdag has low popularity. Tekirdag has low season in February. \nThessaloniki has low popularity. Thessaloniki has low season in February. \nTrabzon has low popularity. Trabzon has low season in February. \nUzhhorod has low popularity. Uzhhorod has low season in February. \nValladolid has low popularity. Valladolid has low season in February. \nVan has low popularity. Van has low season in February. \nVasteras has low popularity. Vasteras has low season in February. \nVinnytsia has low popularity. Vinnytsia has low season in February. \nVitoria-Gasteiz has low popularity. Vitoria-Gasteiz has low season in February. \nVladikavkaz has low popularity. Vladikavkaz has low season in February. \nZaporizhzhia has low popularity. Zaporizhzhia has low season in February. \nZielona Gora has low popularity. Zielona Gora has low season in February. \nBatman has low popularity. Batman has medium season in February. \nErzurum has low popularity. Erzurum has high season in February. \n',
 'city': ['Adana',
  'Adiyaman',
  'Agri',
  'Arad',
  'Arkhangelsk',
  'Bacau',
  'Baia Mare',
  'Balikesir',
  'Brest',
  'Burgas',
  'Canakkale',
  'Craiova',
  'Debrecen',
  'Denizli',
  'Diyarbakir',
  'Elazig',
  'Erzincan',
  'Eskisehir',
  'Gaziantep',
  'Iasi',
  'Ioannina',
  'Isparta',
  'Jonkoping',
  'Kahramanmaras',
  'Kars',
  'Kayseri',
  'Konya',
  'Kosice',
  'Linkoping',
  'Malatya',
  'Miskolc',
  'Mykolaiv',
  'Nalchik',
  'Nevsehir',
  'Nis',
  'Orebro',
  'Orleans',
  'Rivne',
  'Rzeszow',
  'Samsun',
  'Sanliurfa',
  'Sevilla',
  'Siirt',
  'Sivas',
  'Syktyvkar',
  'Targu-Mures',
  'Tekirdag',
  'Thessaloniki',
  'Trabzon',
  'Uzhhorod',
  'Valladolid',
  'Van',
  'Vasteras',
  'Vinnytsia',
  'Vitoria-Gasteiz',
  'Vladikavkaz',
  'Zaporizhzhia',
  'Zielona Gora',
  'Batman',
  'Erzurum'],
 'query_v': 'Cheap European city break in February.\n',
 'query_p0': 'European city break in February, less crowded destinations.\n',
 'query_p1': 'Best European cities for intense physical training and recovery with easy access to ice rinks?\n'}

In [62]:
data = []
for q in queries:
    query_v = q.get('query_v')
    cities = sorted(q.get('city', []))[:5]
    data.append({'config_id': q.get('config_id'), 'query_v': query_v, 'top5_cities': cities})

df = pd.DataFrame(data)
print(df.shape)
df.head()

(2302, 3)

,config_id,query_v,top5_cities
0,c_p_0_pop_low_easy,Cheap European city break in February.\n,"[Adana, Adiyaman, Agri, Arad, Arkhangelsk]"
1,c_p_0_pop_low_medium,"Suggest some less-known, budget-friendly Europ...","[Adana, Craiova, Konya, Rivne, Sivas]"
2,c_p_0_pop_low_hard,Trip to a less-visited European city with hist...,"[Ioannina, Kars, Malatya, Syktyvkar]"
3,c_p_0_pop_low_sustainable,Low budget European city break in April with g...,"[Craiova, Gaziantep]"
4,c_p_0_pop_medium_easy,European city break in January with medium cro...,"[Aalborg, Ancona, Astrakhan, Bari, Belgorod]"

In [48]:
# df.drop_duplicates(subset=["top5_cities"], inplace=True)

In [63]:
df.shape

(2302, 3)

In [64]:
df.head()

,config_id,query_v,top5_cities
0,c_p_0_pop_low_easy,Cheap European city break in February.\n,"[Adana, Adiyaman, Agri, Arad, Arkhangelsk]"
1,c_p_0_pop_low_medium,"Suggest some less-known, budget-friendly Europ...","[Adana, Craiova, Konya, Rivne, Sivas]"
2,c_p_0_pop_low_hard,Trip to a less-visited European city with hist...,"[Ioannina, Kars, Malatya, Syktyvkar]"
3,c_p_0_pop_low_sustainable,Low budget European city break in April with g...,"[Craiova, Gaziantep]"
4,c_p_0_pop_medium_easy,European city break in January with medium cro...,"[Aalborg, Ancona, Astrakhan, Bari, Belgorod]"

In [65]:
df.rename(columns={'query_v': 'query'}, inplace=True)

In [66]:
df[["config_id", "query"]].to_csv(f"../../data/conv-trs/ecir-2026/selected_queries/{model_name}_all_queries.csv", index=False)

In [67]:
df

,config_id,query,top5_cities
0,c_p_0_pop_low_easy,Cheap European city break in February.\n,"[Adana, Adiyaman, Agri, Arad, Arkhangelsk]"
1,c_p_0_pop_low_medium,"Suggest some less-known, budget-friendly Europ...","[Adana, Craiova, Konya, Rivne, Sivas]"
2,c_p_0_pop_low_hard,Trip to a less-visited European city with hist...,"[Ioannina, Kars, Malatya, Syktyvkar]"
3,c_p_0_pop_low_sustainable,Low budget European city break in April with g...,"[Craiova, Gaziantep]"
4,c_p_0_pop_medium_easy,European city break in January with medium cro...,"[Aalborg, Ancona, Astrakhan, Bari, Belgorod]"
...,...,...,...
2297,c_p_199_pop_medium_sustainable,"Looking for a less-crowded, budget-friendly ci...","[Bursa, Lviv, Plovdiv, Rijeka, Szczecin]"
2298,c_p_199_pop_high_easy,Expensive and popular European city break?\n,"[Amsterdam, Barcelona, Bergen, Berlin, Bologna]"
2299,c_p_199_pop_high_medium,Medium budget European city break in September...,"[Belgrade, Bratislava, Budapest, Nicosia, Sara..."
2300,c_p_199_pop_high_hard,Scenic European city break in October with out...,"[Amsterdam, Barcelona, Bergen, Berlin, Bologna]"
2301,c_p_199_pop_high_sustainable,Medium budget European city break in March wit...,"[Belgrade, Bratislava, Budapest, Nicosia, Sara..."